### ISSUE TITLE
How to build for Linux amd64?

### ISSUE THREAD

**Issue by joelmaxuel** [djm34/ccminer-lyra#1]
...because configure is broken:

joel@cybaryme:~/Downloads/ccminer-lyra-0.3$ ./configure 
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."
joel@cybaryme:~/Downloads/ccminer-lyra-0.3$

**Comment by djm34** [comment]
autoreconf -fvi
./configure
make

**Comment by joelmaxuel** [comment]
Okay, and then....

g++ -DHAVE_CONFIG_H -I.  -fopenmp  -pthread -fno-strict-aliasing -I./compat/jansson -I/usr/local/cuda/include  -DSCRYPT_KECCAK512 -DSCRYPT_CHACHA -DSCRYPT_CHOOSE_COMPILETIME   -g -O2 -MT ccminer-cuda.o -MD -MP -MF .deps/ccminer-cuda.Tpo -c -o ccminer-cuda.o `test -f 'cuda.cpp' || echo './'`cuda.cpp
mv -f .deps/ccminer-cuda.Tpo .deps/ccminer-cuda.Po
nvcc -gencode=arch=compute_52,code=\"sm_52,compute_52\" -gencode=arch=compute_50,code=\"sm_50,compute_50\" -gencode=arch=compute_35,code=\"sm_35,compute_35\" -I/usr/local/cuda/include -I. -I./compat/jansson --ptxas-options="-v" --maxrregcount=128 -o heavy/heavy.o -c heavy/heavy.cu
nvcc fatal   : Unsupported gpu architecture 'compute_52'
Makefile:2062: recipe for target 'heavy/heavy.o' failed
make[2]: *** [heavy/heavy.o] Error 255
make[2]: Leaving directory '/home/joel/Downloads/ccminer-lyra-0.3'
Makefile:1612: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/joel/Downloads/ccminer-lyra-0.3'
Makefile:555: recipe for target 'all' failed
make: *** [all] Error 2

I am using Cuda 6.5.  Should I be using a newer version?

**Comment by djm34** [comment]
use a more recent version of cuda 6.5, one which support compute 5.2 (ie the gtx980) or remove that line so it compiles only for 3.5 or 5.0 (in Makefile.am, use again autoreconf; ./configure if you do that)

**Comment by joelmaxuel** [comment]
Sorry to bother you with this.  Took option 2, and got a bit further:

nvcc -gencode=arch=compute_50,code=\"sm_50,compute_50\" -gencode=arch=compute_35,code=\"sm_35,compute_35\" -I/usr/local/cuda/include -I. -I./compat/jansson --ptxas-options="-v" --maxrregcount=128 -o lyra2/cuda_lyra2.o -c lyra2/cuda_lyra2.cu
./cuda_vector.h(1196): error: more than one instance of overloaded function "__shfl" matches the argument list:
            function "__shfl(int, int, int)"
            function "__shfl(float, int, int)"
            argument types are: (const unsigned int, int)

./cuda_vector.h(1197): error: more than one instance of overloaded function "__shfl" matches the argument list:
            function "__shfl(int, int, int)"
            function "__shfl(float, int, int)"
            argument types are: (const unsigned int, int)

./cuda_vector.h(1198): error: more than one instance of overloaded function "__shfl" matches the argument list:
            function "__shfl(int, int, int)"
            function "__shfl(float, int, int)"
            argument types are: (const unsigned int, int)

./cuda_vector.h(1199): error: more than one instance of overloaded function "__shfl" matches the argument list:
            function "__shfl(int, int, int)"
            function "__shfl(float, int, int)"
            argument types are: (const unsigned int, int)

./cuda_vector.h(1200): error: more than one instance of overloaded function "__shfl" matches the argument list:
            function "__shfl(int, int, int)"
            function "__shfl(float, int, int)"
            argument types are: (const unsigned int, int)

./cuda_vector.h(1201): error: more than one instance of overloaded function "__shfl" matches the argument list:
            function "__shfl(int, int, int)"
            function "__shfl(float, int, int)"
            argument types are: (const unsigned int, int)

./cuda_vector.h(1202): error: more than one instance of overloaded function "__shfl" matches the argument list:
            function "__shfl(int, int, int)"
            function "__shfl(float, int, int)"
            argument types are: (const unsigned int, int)

./cuda_vector.h(1203): error: more than one instance of overloaded function "__shfl" matches the argument list:
            function "__shfl(int, int, int)"
            function "__shfl(float, int, int)"
            argument types are: (const unsigned int, int)

./cuda_vector.h(1213): error: more than one instance of overloaded function "__shfl" matches the argument list:
            function "__shfl(int, int, int)"
            function "__shfl(float, int, int)"
            argument types are: (unsigned int, int)

./cuda_vector.h(1214): error: more than one instance of overloaded function "__shfl" matches the argument list:
            function "__shfl(int, int, int)"
            function "__shfl(float, int, int)"
            argument types are: (unsigned int, int)

./cuda_vector.h(1217): error: more than one instance of overloaded function "__shfl" matches the argument list:
            function "__shfl(int, int, int)"
            function "__shfl(float, int, int)"
            argument types are: (unsigned int, int)

./cuda_vector.h(1218): error: more than one instance of overloaded function "__shfl" matches the argument list:
            function "__shfl(int, int, int)"
            function "__shfl(float, int, int)"
            argument types are: (unsigned int, int)

./cuda_vector.h(1221): error: more than one instance of overloaded function "__shfl" matches the argument list:
            function "__shfl(int, int, int)"
            function "__shfl(float, int, int)"
            argument types are: (unsigned int, int)

./cuda_vector.h(1222): error: more than one instance of overloaded function "__shfl" matches the argument list:
            function "__shfl(int, int, int)"
            function "__shfl(float, int, int)"
            argument types are: (unsigned int, int)

./cuda_vector.h(1225): error: more than one instance of overloaded function "__shfl" matches the argument list:
            function "__shfl(int, int, int)"
            function "__shfl(float, int, int)"
            argument types are: (unsigned int, int)

./cuda_vector.h(1226): error: more than one instance of overloaded function "__shfl" matches the argument list:
            function "__shfl(int, int, int)"
            function "__shfl(float, int, int)"
            argument types are: (unsigned int, int)

lyra2/cuda_lyra2.cu(27): warning: function "Gfunc_v35(uint2 &, uint2 &, uint2 &, uint2 &)" was declared but never referenced

16 errors detected in the compilation of "/tmp/tmpxft_0000759d_00000000-9_cuda_lyra2.compute_35.cpp1.ii".
Makefile:2063: recipe for target 'lyra2/cuda_lyra2.o' failed
make[2]: *** [lyra2/cuda_lyra2.o] Error 2
make[2]: Leaving directory '/home/joel/Downloads/ccminer-lyra-0.3'
Makefile:1613: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/joel/Downloads/ccminer-lyra-0.3'
Makefile:556: recipe for target 'all' failed
make: *** [all] Error 2

Maybe option 1 is sounding like the better choice?

**Comment by djm34** [comment]
yeah probably go with option1, don't have much time at the moment...

**Comment by joelmaxuel** [comment]
Okay, thanks.  Closing so I don't take up any more time.  ;)
