### ISSUE TITLE
optimized ?

### ISSUE THREAD

**Issue by altagir** [djm34/ccminer-lyra#11]
switching from ccminer to ccminer-lyra decrease performance from 330 Mh/s to 60 Mh/s

how is this optimized?

**Comment by djm34** [comment]
what lyra version ? on what? with what ? etc...

330MH/s sounds a bit high however... 
(by the way did you pay attention that this version is three years old ? and haven't been touched since 3 years... ? This should be a clue that this version is somewhat deprecated...)

**Comment by altagir** [comment]
Yes I realized after it was 3 years old, I will not use it amymore
I was just comparing  ccminer (git - 2.2.5) with various other optimized repos.
 
I was mining XVG on suprnova (lyra2v2 algo)

**Comment by djm34** [comment]
yeah, it was optimized 3 years ago lol
